"""
Supabase Service for database operations
"""
from supabase import create_client, Client
from typing import Optional, Dict, Any, List
from datetime import date, datetime
import os
import tempfile
import aiofiles
from ..config import settings

class SupabaseService:
    def __init__(self):
        self.client: Client = create_client(
            settings.SUPABASE_URL,
            settings.SUPABASE_SERVICE_KEY
        )
    
    async def get_template(
        self,
        organization_id: str,
        template_id: Optional[str] = None
    ) -> Optional[Dict[str, Any]]:
        """Get invoice template"""
        try:
            query = self.client.table("invoice_templates").select("*").eq("organization_id", organization_id)
            
            if template_id:
                query = query.eq("id", template_id)
            else:
                # Get default template
                query = query.eq("is_default", True)
            
            response = query.single().execute()
            return response.data if response.data else None
            
        except Exception as e:
            # If no default template, try to get any template
            if not template_id:
                try:
                    response = self.client.table("invoice_templates").select("*").eq("organization_id", organization_id).limit(1).execute()
                    if response.data and len(response.data) > 0:
                        return response.data[0]
                except:
                    pass
            return None
    
    async def get_invoice_data(
        self,
        organization_id: str,
        customer_id: str,
        period_start: date,
        period_end: date
    ) -> Optional[Dict[str, Any]]:
        """Get invoice data including rentals and line items"""
        try:
            # Get customer info
            customer = self.client.table("customers").select("*").eq("CustomerListID", customer_id).eq("organization_id", organization_id).single().execute()
            
            # Get active rentals
            rentals = self.client.table("rentals").select("*, bottles(*)").eq("customer_id", customer_id).eq("status", "active").execute()
            
            # Get invoice settings
            settings = self.client.table("invoice_settings").select("*").eq("organization_id", organization_id).single().execute()
            
            # Get organization info
            org = self.client.table("organizations").select("*").eq("id", organization_id).single().execute()
            
            # Calculate line items
            line_items = []
            subtotal = 0
            
            for rental in rentals.data:
                rental_start = date.fromisoformat(rental['rental_start_date'])
                days = (period_end - max(rental_start, period_start)).days + 1
                
                # Get rate
                rate = rental.get('rental_amount') or rental.get('daily_rate', 0)
                if rental.get('billing_frequency') == 'yearly':
                    rate = rate / 365  # Convert yearly to daily
                
                total = days * rate
                subtotal += total
                
                line_items.append({
                    'description': rental.get('bottles', {}).get('description', 'Cylinder'),
                    'barcode': rental.get('bottle_barcode', ''),
                    'serial_number': rental.get('bottles', {}).get('serial_number', ''),
                    'rental_start_date': rental['rental_start_date'],
                    'rental_days': days,
                    'quantity': 1,
                    'unit_price': rate,
                    'total_price': total
                })
            
            # Calculate tax
            tax_rate = settings.data.get('tax_rate', 0.11) if settings.data else 0.11
            tax_amount = subtotal * tax_rate
            total_amount = subtotal + tax_amount
            
            # Invoice number will be auto-generated by database trigger, but we can show what it will be
            invoice_prefix = settings.data.get('invoice_prefix', 'INV') if settings.data else 'INV'
            next_number = settings.data.get('next_invoice_number', 1) if settings.data else 1
            invoice_number = f"{invoice_prefix}{str(next_number).zfill(6)}"
            
            # Build organization address
            org_address_parts = [
                org.data.get('address', ''),
                org.data.get('city', ''),
                org.data.get('state', ''),
                org.data.get('postal_code', '')
            ]
            org_address = ', '.join([p for p in org_address_parts if p])
            
            return {
                'customer_id': customer_id,
                'customer_name': customer.data.get('name', ''),
                'customer_address': customer.data.get('address', ''),
                'customer_email': customer.data.get('email', ''),
                'invoice_number': invoice_number,
                'invoice_date': date.today().isoformat(),
                'invoice_period_start': period_start.isoformat(),
                'invoice_period_end': period_end.isoformat(),
                'line_items': line_items,
                'subtotal': subtotal,
                'tax_amount': tax_amount,
                'tax_rate': tax_rate,
                'total_amount': total_amount,
                'organization_name': org.data.get('name', '') if org.data else '',
                'organization_address': org_address,
                'organization_phone': org.data.get('phone', '') if org.data else '',
                'organization_email': org.data.get('email', '') if org.data else '',
                'organization_logo_url': org.data.get('logo_url', '') if org.data else '',
                'payment_terms': settings.data.get('payment_terms', 'Net 30') if settings.data else 'Net 30',
                'invoice_notes': settings.data.get('invoice_notes', '') if settings.data else ''
            }
            
        except Exception as e:
            print(f"Error getting invoice data: {e}")
            return None
    
    async def get_invoice_data_from_id(
        self,
        invoice_id: str,
        organization_id: str
    ) -> Optional[Dict[str, Any]]:
        """Get invoice data from invoice ID"""
        try:
            invoice = self.client.table("rental_invoices").select("*, invoice_line_items(*)").eq("id", invoice_id).eq("organization_id", organization_id).single().execute()
            
            if not invoice.data:
                return None
            
            invoice_data = invoice.data
            line_items = invoice_data.get('invoice_line_items', [])
            
            return {
                'customer_id': invoice_data.get('customer_id', ''),
                'customer_name': invoice_data.get('customer_name', ''),
                'customer_address': invoice_data.get('customer_address', ''),
                'customer_email': invoice_data.get('customer_email', ''),
                'invoice_number': invoice_data.get('invoice_number', ''),
                'invoice_date': invoice_data.get('invoice_date', ''),
                'invoice_period_start': invoice_data.get('invoice_period_start', ''),
                'invoice_period_end': invoice_data.get('invoice_period_end', ''),
                'line_items': line_items,
                'subtotal': float(invoice_data.get('subtotal', 0)),
                'tax_amount': float(invoice_data.get('tax_amount', 0)),
                'total_amount': float(invoice_data.get('total_amount', 0)),
                'notes': invoice_data.get('notes', '')
            }
            
        except Exception as e:
            print(f"Error getting invoice data from ID: {e}")
            return None
    
    async def get_invoice_by_id(
        self,
        invoice_id: str,
        organization_id: str
    ) -> Optional[Dict[str, Any]]:
        """Get invoice by ID"""
        try:
            response = self.client.table("rental_invoices").select("*").eq("id", invoice_id).eq("organization_id", organization_id).single().execute()
            return response.data if response.data else None
        except Exception as e:
            return None
    
    async def upload_pdf(
        self,
        file_path: str,
        organization_id: str,
        invoice_number: str
    ) -> str:
        """Upload PDF to Supabase Storage"""
        try:
            file_name = f"{invoice_number}.pdf"
            storage_path = f"{organization_id}/{file_name}"
            
            with open(file_path, 'rb') as f:
                self.client.storage.from_(settings.SUPABASE_STORAGE_BUCKET).upload(
                    path=storage_path,
                    file=f,
                    file_options={"content-type": "application/pdf", "upsert": "true"}
                )
            
            # Get public URL
            url_response = self.client.storage.from_(settings.SUPABASE_STORAGE_BUCKET).get_public_url(storage_path)
            return url_response
            
        except Exception as e:
            print(f"Error uploading PDF: {e}")
            raise
    
    async def download_pdf(
        self,
        pdf_url: str
    ) -> str:
        """Download PDF from URL to temporary file"""
        try:
            import httpx
            async with httpx.AsyncClient() as client:
                response = await client.get(pdf_url)
                response.raise_for_status()
                
                # Save to temp file
                temp_file = tempfile.NamedTemporaryFile(delete=False, suffix='.pdf')
                async with aiofiles.open(temp_file.name, 'wb') as f:
                    await f.write(response.content)
                
                return temp_file.name
                
        except Exception as e:
            print(f"Error downloading PDF: {e}")
            raise
    
    async def save_invoice(
        self,
        organization_id: str,
        invoice_data: Dict[str, Any],
        template_id: Optional[str],
        pdf_url: str,
        user_id: str
    ) -> str:
        """Save or update invoice record"""
        try:
            invoice_record = {
                'organization_id': organization_id,
                'invoice_number': invoice_data['invoice_number'],
                'customer_id': invoice_data['customer_id'],
                'customer_name': invoice_data['customer_name'],
                'customer_address': invoice_data.get('customer_address'),
                'customer_email': invoice_data.get('customer_email'),
                'invoice_date': invoice_data['invoice_date'],
                'invoice_period_start': invoice_data['invoice_period_start'],
                'invoice_period_end': invoice_data['invoice_period_end'],
                'subtotal': invoice_data['subtotal'],
                'tax_amount': invoice_data['tax_amount'],
                'total_amount': invoice_data['total_amount'],
                'pdf_url': pdf_url,
                'template_id': template_id,
                'status': 'draft',
                'created_by': user_id
            }
            
            # Check if invoice exists
            existing = self.client.table("rental_invoices").select("id").eq("invoice_number", invoice_data['invoice_number']).eq("organization_id", organization_id).execute()
            
            if existing.data and len(existing.data) > 0:
                # Update existing
                invoice_id = existing.data[0]['id']
                self.client.table("rental_invoices").update(invoice_record).eq("id", invoice_id).execute()
            else:
                # Create new
                response = self.client.table("rental_invoices").insert(invoice_record).execute()
                invoice_id = response.data[0]['id'] if response.data else None
            
            # Save line items
            if invoice_id:
                # Delete existing line items
                self.client.table("invoice_line_items").delete().eq("invoice_id", invoice_id).execute()
                
                # Insert new line items
                line_items = []
                for item in invoice_data.get('line_items', []):
                    line_items.append({
                        'invoice_id': invoice_id,
                        'line_type': 'rental',
                        'description': item.get('description', ''),
                        'cylinder_id': item.get('cylinder_id'),
                        'barcode': item.get('barcode', ''),
                        'rental_start_date': item.get('rental_start_date'),
                        'rental_days': item.get('rental_days'),
                        'quantity': item.get('quantity', 1),
                        'unit_price': item.get('unit_price', 0),
                        'total_price': item.get('total_price', 0)
                    })
                
                if line_items:
                    self.client.table("invoice_line_items").insert(line_items).execute()
            
            return invoice_id
            
        except Exception as e:
            print(f"Error saving invoice: {e}")
            raise
    
    async def update_invoice_status(
        self,
        invoice_id: str,
        status: str
    ):
        """Update invoice status"""
        try:
            update_data = {'status': status}
            if status == 'sent':
                update_data['sent_at'] = datetime.now().isoformat()
            elif status == 'paid':
                update_data['paid_at'] = datetime.now().isoformat()
            
            self.client.table("rental_invoices").update(update_data).eq("id", invoice_id).execute()
            
        except Exception as e:
            print(f"Error updating invoice status: {e}")
            raise

